"""
🛒 Product Return Predictor — Streamlit UI
Run:  streamlit run app.py
Requires:  model/return_predictor.joblib  &  model/model_metadata.json
           (generated by the notebook)
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import json
import os

# ── Page config ──────────────────────────────────────────────────
st.set_page_config(
    page_title="Product Return Predictor",
    page_icon="🛒",
    layout="centered",
)

# ── Load model & metadata ───────────────────────────────────────
MODEL_PATH = "model/return_predictor.joblib"
META_PATH  = "model/model_metadata.json"


@st.cache_resource
def load_model():
    if not os.path.exists(MODEL_PATH):
        return None, None
    model = joblib.load(MODEL_PATH)
    with open(META_PATH) as f:
        meta = json.load(f)
    return model, meta


model, meta = load_model()

# ── Header ───────────────────────────────────────────────────────
st.title("🛒 Product Return Predictor")
clf_title = type(model.named_steps["classifier"]).__name__ if model and hasattr(model, "named_steps") else "Machine Learning"
st.markdown(
    f"Predict whether an e-commerce order will be **returned** "
    f"using a production **{clf_title}** pipeline."
)
st.divider()

if model is None:
    st.error(
        "**Model not found!** Please run the notebook first to "
        "generate `model/return_predictor.joblib`."
    )
    st.stop()

# ── Helpers ──────────────────────────────────────────────────────
cat_opts = meta["categorical_options"]
num_ranges = meta["numerical_ranges"]


def get_range(col, key, default=0):
    """Safely get a numerical range value from metadata."""
    return num_ranges.get(col, {}).get(key, default)


# ── Input form ───────────────────────────────────────────────────
with st.form("predict_form"):

    # ─── Product Details ─────────────────────────────────────────
    st.subheader("📦 Product Details")
    p1, p2, p3 = st.columns(3)

    with p1:
        product_category = st.selectbox(
            "Product Category", cat_opts.get("product_category", [])
        )
        product_price = st.number_input(
            "Product Price (₹)", min_value=1.0,
            max_value=100_000.0, value=600.0, step=10.0,
        )
        product_rating = st.slider(
            "Product Rating ⭐", 1.0, 5.0, 4.0, 0.1
        )

    with p2:
        sub_category = st.selectbox(
            "Sub Category", cat_opts.get("sub_category", [])
        )
        discount_percent = st.slider(
            "Discount (%)", 0.0, 70.0, 20.0, 0.5
        )
        review_count = st.number_input(
            "Review Count", min_value=0, max_value=200, value=70
        )

    with p3:
        brand = st.selectbox("Brand", cat_opts.get("brand", []))
        defect_rate = st.slider(
            "Defect Rate", 0.00, 0.40, 0.05, 0.01
        )
        quantity = st.slider("Quantity", 1, 5, 1)

    # ─── Seller & Logistics ──────────────────────────────────────
    st.subheader("🏪 Seller & Logistics")
    s1, s2, s3 = st.columns(3)

    with s1:
        seller_rating = st.slider(
            "Seller Rating ⭐", 1.0, 5.0, 4.0, 0.1
        )
        fulfillment_type = st.selectbox(
            "Fulfillment Type",
            cat_opts.get("fulfillment_type", []),
        )

    with s2:
        payment_method = st.selectbox(
            "Payment Method", cat_opts.get("payment_method", [])
        )
        shipping_distance_km = st.number_input(
            "Shipping Distance (km)",
            min_value=1.0, max_value=1500.0, value=500.0, step=10.0,
        )

    with s3:
        product_page_views = st.number_input(
            "Product Page Views", min_value=1, max_value=50, value=12
        )
        customer_support_calls = st.number_input(
            "Support Calls", min_value=0, max_value=10, value=0
        )
        chat_interactions = st.number_input(
            "Chat Interactions", min_value=0, max_value=10, value=0
        )

    # ─── Order Properties ────────────────────────────────────────
    st.subheader("📋 Order Properties")
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        fragile_item = st.checkbox("Fragile Item")
    with c2:
        warranty_available = st.checkbox("Warranty Available")
    with c3:
        delayed_delivery = st.checkbox("Delayed Delivery")
    with c4:
        wishlist_before_purchase = st.checkbox("From Wishlist")

    # ─── Submit ──────────────────────────────────────────────────
    submitted = st.form_submit_button(
        "🔮  Predict Return", use_container_width=True
    )

# ── Prediction ───────────────────────────────────────────────────
if submitted:
    # Feature engineering (must match the notebook)
    log_price = float(np.log1p(product_price))
    total_support_contacts = customer_support_calls + chat_interactions

    # Build a single-row DataFrame with the exact columns
    # the pipeline expects
    input_df = pd.DataFrame([{
        # numerical
        "discount_percent":       discount_percent,
        "product_rating":         product_rating,
        "review_count":           float(review_count),
        "defect_rate":            defect_rate,
        "seller_rating":          seller_rating,
        "quantity":               quantity,
        "shipping_distance_km":   shipping_distance_km,
        "product_page_views":     float(product_page_views),
        "total_support_contacts": float(total_support_contacts),
        "log_price":              log_price,
        # categorical
        "product_category":       product_category,
        "sub_category":           sub_category,
        "brand":                  brand,
        "fulfillment_type":       fulfillment_type,
        "payment_method":         payment_method,
        # binary
        "fragile_item":           int(fragile_item),
        "warranty_available":     int(warranty_available),
        "delayed_delivery":       int(delayed_delivery),
        "wishlist_before_purchase": int(wishlist_before_purchase),
    }])

    prediction = model.predict(input_df)[0]
    probabilities = model.predict_proba(input_df)[0]
    return_prob = float(probabilities[1])
    keep_prob   = float(probabilities[0])

    st.divider()

    if prediction == 1:
        st.error("### ⚠️  LIKELY TO BE RETURNED")
        col_a, col_b = st.columns(2)
        col_a.metric("Return Probability", f"{return_prob:.1%}")
        col_b.metric("Keep Probability", f"{keep_prob:.1%}")
    else:
        st.success("### ✅  NOT LIKELY TO BE RETURNED")
        col_a, col_b = st.columns(2)
        col_a.metric("Keep Probability", f"{keep_prob:.1%}")
        col_b.metric("Return Probability", f"{return_prob:.1%}")

    # Probability bar
    st.progress(return_prob, text=f"Return risk: {return_prob:.1%}")

    # Show the input summary
    with st.expander("📄 View input data sent to model"):
        st.dataframe(input_df.T.rename(columns={0: "Value"}))

# ── Footer ───────────────────────────────────────────────────────
st.divider()
clf_name = type(model.named_steps["classifier"]).__name__ if hasattr(model, "named_steps") else "Trained"
st.caption(
    f"Model: {clf_name} Pipeline · "
    "Built with scikit-learn & Streamlit"
)

